blank_issues_enabled: true
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/IBM/ims-explorer-about/blob/main/README.md
    about: Check the documentation for help and guides
  - name: ðŸ’¬ Discussions
    url: https://github.ibm.com/ims/ims-explorer-about/discussions
    about: Ask questions and discuss with the community
